[project]
name = "website"
version = "1.0.0"
description = "SJSU Library Website Mock Up"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"